version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: portfolio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aarthi@2204
      MYSQL_DATABASE: portfolio_db
    ports:
      - "3306:3306"
    volumes:
      - portfolio_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: portfolio-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Aarthi@2204
      DB_NAME: portfolio_db
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["node", "server.js"]

volumes:
  portfolio_db_data:
